# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            portfolio-site
tagline:          'A Jekyll theme'
description:      'A brazen two-column'
url:              http://vikumar.github.io
baseurl:          /

author:
  name:           ''
  url:            https://github.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vigneshk01/vikumar.github.io
