# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Data Science Portfolio
tagline:          'My Portfolio'
description:      'Details of my Data Science projects'
url:              http://vigneshk01.github.io
baseurl:          /
plugins:          [jekyll-paginate]

author:
  name:           ''
  url:            https://github.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vigneshk01/vigneshk01.github.io
